---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# ceramic

The goal of ceramic is to ...

## Installation

You can install the dev version of ceramic from  Github ...


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(sf)     ## st_bbox, st_crs
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(slippymath)
my_bbox <-
  st_bbox(c(xmin = 130,
            xmax = 146,
            ymin = -36,
            ymax = -28),
          crs = st_crs("+proj=longlat +ellps=WGS84"))

tile_grid <- bb_to_tg(my_bbox, max_tiles = 36)
zoom <- tile_grid$zoom

mapbox_query_string <-
  paste0("https://api.mapbox.com/v4/mapbox.satellite/{zoom}/{x}/{y}.jpg90",
         "?access_token=",
         Sys.getenv("MAPBOX_API_KEY"))

library(ceramic)
files <- unlist(down_loader(tile_grid, mapbox_query_string))
tibble::tibble(filename = gsub(normalizePath(rappdirs::user_cache_dir(), winslash = "/"), 
                               "", 
                               normalizePath(files, winslash = "/")))

library(raster)
br <- lapply(files, raster::brick)

for (i in seq_along(br)) {
  br[[i]] <- setExtent(br[[i]],  
                       mercator_tile_extent(tile_grid$tiles$x[i], tile_grid$tiles$y[i], zoom = zoom))
}

im <- purrr::reduce(br, raster::merge)
plotRGB(im)
# devtools::install_github("mdsumner/ozmaps")
dat <- sf::st_transform(ozmaps::ozmap_states, "+proj=merc +a=6378137 +b=6378137")
plot(dat$geometry, add = TRUE, lwd = 5, border = "dodgerblue")
```



Please note that the 'ceramic' project is released with a [Contributor Code of Conduct](CODE_OF_CONDUCT.md). By contributing to this project, you agree to abide by its terms.



